SET IDENTITY_INSERT dbo.Orders ON

INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (1, 6, 10, 7)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (2, 3, 7, 11)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (3, 0, 9, 7)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (4, 6, 3, 12)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (5, 7, 2, 14)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (6, 1, 2, 10)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (7, 4, 3, 1)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (8, 5, 9, 8)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (9, 6, 4, 7)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (10, 0, 2, 1)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (11, 0, 10, 3)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (12, 5, 2, 1)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (13, 6, 10, 13)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (14, 1, 9, 10)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (15, 9, 2, 8)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (16, 1, 3, 7)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (17, 1, 8, 13)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (18, 0, 4, 8)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (19, 4, 9, 7)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (20, 7, 2, 15)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (21, 1, 2, 1)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (22, 0, 6, 11)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (23, 1, 10, 3)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (24, 10, 4, 2)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (25, 7, 9, 4)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (26, 4, 2, 2)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (27, 0, 2, 9)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (28, 6, 5, 15)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (29, 10, 3, 7)
INSERT dbo.Orders(Id, Taxes, SubTotal, AccountId) VALUES (30, 7, 8, 11)

SET IDENTITY_INSERT dbo.Orders OFF
