SET IDENTITY_INSERT dbo.OrderProducts ON

INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (1, 15, 14, 16)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (2, 6, 5, 17)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (3, 13, 13, 9)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (4, 3, 2, 6)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (5, 10, 10, 8)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (6, 14, 14, 11)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (7, 3, 3, 9)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (8, 7, 7, 3)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (9, 4, 4, 18)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (10, 11, 11, 13)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (11, 1, 1, 18)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (12, 8, 8, 12)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (13, 16, 15, 19)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (14, 12, 11, 1)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (15, 9, 8, 13)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (16, 13, 12, 15)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (17, 12, 12, 17)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (18, 9, 9, 8)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (19, 5, 5, 10)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (20, 7, 6, 11)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (21, 2, 2, 14)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (22, 10, 9, 1)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (23, 6, 6, 12)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (24, 14, 13, 10)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (25, 4, 3, 20)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (26, 11, 10, 20)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (27, 15, 15, 3)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (28, 5, 4, 18)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (29, 8, 7, 6)
INSERT dbo.OrderProducts(Id, OrderId, ProductId, Quantity) VALUES (30, 2, 1, 20)

SET IDENTITY_INSERT dbo.OrderProducts OFF
